# Generated by Django 5.1 on 2026-01-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_course_image_course_image_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
