# Generated by Django 5.1 on 2026-01-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_course_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='age_group',
            field=models.CharField(choices=[('3-16', '3-16 yaş'), ('16+', '16+ yaş')], default='16+', max_length=10),
        ),
    ]
