# Generated by Django 5.1 on 2026-01-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_course_age_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('tedbir', 'Tədbir'), ('yaris', 'Yarış')], max_length=20)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
