# Generated by Django 5.1 on 2026-01-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_material_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
